// Generated by CoffeeScript 1.9.1
var canvas, context, draw, findClosest, generate, image, points;

canvas = document.getElementsByTagName('canvas')[0];

context = canvas.getContext('2d');

points = [];

image = context.createImageData(512, 512);

findClosest = function(x, y) {
  var closest, closestDist, dist, i, len, point;
  closest = {
    r: 0,
    g: 0,
    b: 0
  };
  closestDist = 512 * 512;
  for (i = 0, len = points.length; i < len; i++) {
    point = points[i];
    dist = (x - point.x) * (x - point.x) + (y - point.y) * (y - point.y);
    if (dist < closestDist) {
      closestDist = dist;
      closest = point;
    }
  }
  return closest;
};

generate = function() {
  var i, n, point, results;
  points = [];
  results = [];
  for (n = i = 0; i <= 64; n = ++i) {
    point = {
      x: 512 * Math.random(),
      y: 512 * Math.random(),
      r: 255 * Math.random() | 0,
      g: 255 * Math.random() | 0,
      b: 255 * Math.random() | 0
    };
    results.push(points.push(point));
  }
  return results;
};

draw = function() {
  var i, index, j, ms, point, start, x, y;
  start = Date.now();
  for (x = i = 0; i <= 511; x = ++i) {
    for (y = j = 0; j <= 511; y = ++j) {
      point = findClosest(x, y);
      index = (x + y * 512) * 4;
      image.data[index + 0] = point.r;
      image.data[index + 1] = point.g;
      image.data[index + 2] = point.b;
      image.data[index + 3] = 255;
    }
  }
  ms = Date.now() - start;
  context.putImageData(image, 0, 0);
  context.font = '18px consolas';
  context.fillStyle = 'white';
  context.fillText(ms + "ms", 20, 20);
  context.fillText("R to regenerate", 20, 40);
  return requestAnimationFrame(draw);
};

document.onkeyup = function(e) {
  if (e.keyCode === 'R'.charCodeAt(0)) {
    return generate();
  }
};

generate();

requestAnimationFrame(draw);
